vich_uploader:
  db_driver: orm
  mappings:
    page_image:
      uri_prefix: '%app.path.product_images%'
      upload_destination: '%kernel.project_dir%/web/uploads/gallery'
      namer: vich_uploader.namer_uniqid
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    blog_image:
      uri_prefix: '%app.path.blog_images%'
      upload_destination: '%kernel.project_dir%/web/uploads'
      namer: vich_uploader.namer_uniqid
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true