<?php

declare(strict_types=1);

namespace AppBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchPageByTitle(array $params = [])
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->select('p')
        ;

        if (!empty($params['searchPageByTitle'])) {
            $searchPageByTitle = '%'. $params['searchPageByTitle'] . '%';
            $queryBuilder
                ->andWhere('p.title LIKE :searchPageByTitle OR p.alias LIKE :searchPageByTitle')
                ->setParameter('searchPageByTitle', $searchPageByTitle)
            ;
        }
        return $queryBuilder;
    }

    public function countAmountPages(): array
    {
        return $this->createQueryBuilder('p')
            ->select('count(p.id) as countPages')
            ->getQuery()
            ->getResult()
            ;
    }
}
